[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.72.1",
    "boto3>=1.40.69",
    "openai>=2.7.2",
    "playwright>=1.55.0",
    "ulid-py>=1.1.0",
]
